name: nextcloud

services:
  nextcloud:
    image: nextcloud:stable
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    depends_on:
      - database
      - redis
    secrets:
      - postgres_password
      - nextcloud_admin_password

  database:
    image: postgres:latest
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password

  redis:
    image: redis:latest
    restart: always

  collabora:
    image: collabora/code:latest
    restart: always
    ports:
      - 9980:9980
    environment:
      - password_FILE=/run/secrets/collabora_password
      - username=${COLLABORA_USER}
      - extra_params=${COLLABORA_EXTRA_PARAMS}

volumes:
  database:
  nextcloud:


secrets:
  nextcloud_admin_password:
    file: ./credentials/nextcloud_admin_password.txt
  postgres_password:
    file: ./credentials/postgres_password.txt
  collabora_password:
    file: ./credentials/collabora_password.txt
