name: nextcloud

services:
  nextcloud:
    image: gabriel434/nextcloud:latest
    build: .
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - nextcloud:/var/www/html
      - files:/var/www/data
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_database_password
      - REDIS_HOST=redis
      - NEXTCLOUD_DATA_DIR=/var/www/data
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud ${NEXTCLOUD_TRUSTED_DOMAINS}
      - COLLABORA_SSL=${COLLABORA_SSL}
    depends_on:
      - database
      - redis
    secrets:
      - nextcloud_database_password
      - nextcloud_admin_password

  database:
    image: postgres:latest
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_database_password
    secrets:
      - nextcloud_database_password

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data

  collabora:
    image: collabora/code:latest
    restart: always
    ports:
      - ${COLLABORA_PORT}:9980
    environment:
      - password_FILE=/run/secrets/nextcloud_collabora_password
      - username=${COLLABORA_USER}
      - server_name=${COLLABORA_DOMAIN}:${COLLABORA_PORT}
      - extra_params=-o:ssl.enable=${COLLABORA_SSL} ${COLLABORA_EXTRA_PARAMS}
    secrets:
      - nextcloud_collabora_password

volumes:
  database:
  nextcloud:
  files:
    external: ${EXTERNAL_FILES_VOLUME_ENABLED}
    name: ${EXTERNAL_FILES_VOLUME_NAME}
  redis:


secrets:
  nextcloud_admin_password:
    file: ./credentials/nextcloud_admin_password.txt
  nextcloud_database_password:
    file: ./credentials/nextcloud_database_password.txt
  nextcloud_collabora_password:
    file: ./credentials/nextcloud_collabora_password.txt
